#!/usr/bin/env bash

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            2
bspc config focused_border_color    "#81c8be"
bspc config normal_border_color     "#232634"
bspc config presel_border_color     "#ea999c"
bspc config urgent_border_color     "#ef9f76"
bspc config focused_private_border_color "#99d1db"
bspc config window_gap              10

bspc config auto_alternate          true
bspc config auto_cancel             true
bspc config split_ratio             0.52
bspc config single_monocle          true
bspc config borderless_monocle      true
bspc config gapless_monocle         false

bspc config focus_follows_pointer   true
bspc config pointer_follows_pointer false
bspc config pointer_motion_interval 5
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner

bspc rule -r "*"

# polybar

killall -q polybar

polybar bar 2>&1 | tee -a /tmp/polybar.log & disown
